# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mjcv"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ginok"]
  s.date = "2012-03-03"
  s.description = "TODO: longer description of your gem"
  s.email = "miragino@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mjcv.rb",
     "lib/mjcv/cv/base/j1.r.jpg",
     "lib/mjcv/cv/base/j1.t.jpg",
     "lib/mjcv/cv/base/j2.r.jpg",
     "lib/mjcv/cv/base/j2.t.jpg",
     "lib/mjcv/cv/base/j3.r.jpg",
     "lib/mjcv/cv/base/j3.t.jpg",
     "lib/mjcv/cv/base/j4.r.jpg",
     "lib/mjcv/cv/base/j4.t.jpg",
     "lib/mjcv/cv/base/j5.r.jpg",
     "lib/mjcv/cv/base/j5.t.jpg",
     "lib/mjcv/cv/base/j6.r.jpg",
     "lib/mjcv/cv/base/j6.t.jpg",
     "lib/mjcv/cv/base/j7.r.jpg",
     "lib/mjcv/cv/base/j7.t.jpg",
     "lib/mjcv/cv/base/m1.r.jpg",
     "lib/mjcv/cv/base/m1.t.jpg",
     "lib/mjcv/cv/base/m2.r.jpg",
     "lib/mjcv/cv/base/m2.t.jpg",
     "lib/mjcv/cv/base/m3.r.jpg",
     "lib/mjcv/cv/base/m3.t.jpg",
     "lib/mjcv/cv/base/m4.r.jpg",
     "lib/mjcv/cv/base/m4.t.jpg",
     "lib/mjcv/cv/base/m5.r.jpg",
     "lib/mjcv/cv/base/m5.t.jpg",
     "lib/mjcv/cv/base/m6.r.jpg",
     "lib/mjcv/cv/base/m6.t.jpg",
     "lib/mjcv/cv/base/m7.r.jpg",
     "lib/mjcv/cv/base/m7.t.jpg",
     "lib/mjcv/cv/base/m8.r.jpg",
     "lib/mjcv/cv/base/m8.t.jpg",
     "lib/mjcv/cv/base/m9.r.jpg",
     "lib/mjcv/cv/base/m9.t.jpg",
     "lib/mjcv/cv/base/p1.r.jpg",
     "lib/mjcv/cv/base/p1.t.jpg",
     "lib/mjcv/cv/base/p2.r.jpg",
     "lib/mjcv/cv/base/p2.t.jpg",
     "lib/mjcv/cv/base/p3.r.jpg",
     "lib/mjcv/cv/base/p3.t.jpg",
     "lib/mjcv/cv/base/p4.r.jpg",
     "lib/mjcv/cv/base/p4.t.jpg",
     "lib/mjcv/cv/base/p5.r.jpg",
     "lib/mjcv/cv/base/p5.t.jpg",
     "lib/mjcv/cv/base/p6.r.jpg",
     "lib/mjcv/cv/base/p6.t.jpg",
     "lib/mjcv/cv/base/p7.r.jpg",
     "lib/mjcv/cv/base/p7.t.jpg",
     "lib/mjcv/cv/base/p8.r.jpg",
     "lib/mjcv/cv/base/p8.t.jpg",
     "lib/mjcv/cv/base/p9.r.jpg",
     "lib/mjcv/cv/base/p9.t.jpg",
     "lib/mjcv/cv/base/r0.2.jpg",
     "lib/mjcv/cv/base/r0.t.jpg",
     "lib/mjcv/cv/base/s1.r.jpg",
     "lib/mjcv/cv/base/s1.t.jpg",
     "lib/mjcv/cv/base/s2.r.jpg",
     "lib/mjcv/cv/base/s2.t.jpg",
     "lib/mjcv/cv/base/s3.r.jpg",
     "lib/mjcv/cv/base/s3.t.jpg",
     "lib/mjcv/cv/base/s4.r.jpg",
     "lib/mjcv/cv/base/s4.t.jpg",
     "lib/mjcv/cv/base/s5.r.jpg",
     "lib/mjcv/cv/base/s5.t.jpg",
     "lib/mjcv/cv/base/s6.r.jpg",
     "lib/mjcv/cv/base/s6.t.jpg",
     "lib/mjcv/cv/base/s7.r.jpg",
     "lib/mjcv/cv/base/s7.t.jpg",
     "lib/mjcv/cv/base/s8.r.jpg",
     "lib/mjcv/cv/base/s8.t.jpg",
     "lib/mjcv/cv/base/s9.r.jpg",
     "lib/mjcv/cv/base/s9.t.jpg",
     "lib/mjcv/cv/enum.rb",
     "lib/mjcv/cv/filter.rb",
     "lib/mjcv/cv/image_loader.rb",
     "lib/mjcv/cv/model.rb",
     "lib/mjcv/cv/pai.rb",
     "lib/mjcv/cv/paienum.rb",
     "lib/mjcv/cv/selector.rb",
     "lib/mjcv/cv/template_matching.rb",
     "lib/mjcv/cv/template_matching_analyzer.rb",
     "lib/mjcv/cv/template_matching_classifier.rb",
     "lib/mjcv/fitting/least_median_squares_line_fitting.rb",
     "lib/mjcv/fitting/line_fitting.rb",
     "lib/mjcv/geom/point.rb",
     "lib/mjcv/geom/point_op.rb",
     "lib/mjcv/geom/rect.rb",
     "lib/mjcv/geom/rect_op.rb",
     "lib/mjcv/util/card_chooser.rb",
     "test/card_chooser_test.rb",
     "test/cv_test_helper.rb",
     "test/filter_test.rb",
     "test/least_median_squares_line_fitting_test.rb",
     "test/line_fitting_test.rb",
     "test/point_op_test.rb",
     "test/point_test.rb",
     "test/rect_op_test.rb",
     "test/rect_test.rb",
     "test/template_matching_analyzer_test.rb",
     "test/test_helper.rb",
     "test/test_img/3.jpg",
     "test/test_img/59.jpg",
     "test/test_img/73.jpg",
     "test/test_img/8.jpg",
     "test/test_img/81.jpg",
     "test/test_img/92.jpg",
     "test/test_img/94.jpg",
     "test/test_img/DSC_0013.jpg",
     "test/test_img/DSC_0014.jpg",
     "test/test_img/all.jpg",
     "test/test_img/all001.jpg",
     "test/test_img/all_test.jpg",
     "test/test_img/m1.t.jpg",
     "test/test_img/mj_5s_ng_003.jpg",
     "test/test_img/template_matcher_test_target.jpg",
     "test/test_img/template_matcher_test_template.jpg",
     "test/test_img/test001.jpg",
     "test/test_img/test002.jpg",
     "test/test_img/test003.jpg",
     "test/test_img/test004.jpg",
     "test/test_img/test_komagahouse.jpg",
     "test/test_img/test_komagahouse2.jpg",
     "test/test_img/test_komagahouse3.jpg"
  ]
  s.homepage = "http://github.com/ginok/mjcv"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "TODO: one-line summary of your gem"
  s.test_files = [
    "test/card_chooser_test.rb",
     "test/cv_test_helper.rb",
     "test/filter_test.rb",
     "test/least_median_squares_line_fitting_test.rb",
     "test/line_fitting_test.rb",
     "test/point_op_test.rb",
     "test/point_test.rb",
     "test/rect_op_test.rb",
     "test/rect_test.rb",
     "test/template_matching_analyzer_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
